#!/usr/bin/env python
import rospy

import yaml

from filter_tfs.filter_node import Node, main


class ApriltagsNode(Node):

    def __init__(self):
        super().__init__("apriltags_tf_filter")
        parent_frame = rospy.get_param("~parent_frame")
        tags_filename = rospy.get_param("~tags_filename")

        with open(tags_filename, "r") as f:
            config = yaml.safe_load(f)

        for tag in config.get("standalone_tags",[]) + config.get("tag_bundles", []):
            self.add(parent_frame, tag["name"])


if __name__ == "__main__":
    main(ApriltagsNode)
